### ISSUE TITLE
Investigate Raspberry Pi streaming slides to central recording computer

### ISSUE THREAD

**Issue by ldang** [socallinuxexpo/video-capture#7]
Investigate how to use Raspberry Pi to encode and stream video for Linux; prove that it can support the usb-to-composite capture device.

Please reference and update [Raspberry Pi notes wiki](https://github.com/scale-av/video-capture/wiki/Raspberry-pi-notes)

NOTE: We got GStreamer to work, which is great, because otherwise, we would've had to rely on a painfully pre-compiled VLC binary that may not have all the libraries we would'e needed.

**Comment by mproctor13** [comment]
I checked my scripts into pi directory in master branch. I got streaming from v4l2src to work if you start the receive side before the sending side.

**Comment by ldang** [comment]
mproctor:  "Sadly, the Raspberry Pis do not look like they are going to work as

> there usb hardware does not seem to be up to reading uncompressed
> video. Or at least without spending a bunch of time hacking on the kernel."

So we've ruled out Raspberry Pi for this purpose.
It's possible that BeagleBoneBlack would work better.
